### ISSUE TITLE
Integrating bulk ATAC-seq and bulk RNA-seq data

### ISSUE THREAD

**Issue by phoebe460** [Pinlyu3/IReNA-v2#1]
Hello IReNA tool developers,

Thank you for creating this integration network tool. It's pretty neat and I plan on using this for my own research work actually. I have a quick question. I have available bulk ATAC-seq and bulk RNA-seq data, instead of single-cell ATAC-seq and single-cell RNA-seq data, so I was wondering if I can use this tool with that kind of data instead? If so, how do I go about approaching that? If you can let me know, then I would greatly appreciate it. 

Best regards,
Phoebe

**Comment by Pinlyu3** [comment]
Hi Phoebe,
    This pipeline using the scRNA-seq to calculated the gene-gene correlations. I believe that for multiple bulk RNA-seq datasets, there must be lots of tools can do that work. But I can not give you any recommendation because I am not very familiar with such tools.
    For your bulk ATAC-seq datasets, you can use some code in the IReNA part3 module (https://github.com/jiang-junyao/IReNA) to predict TF binding in accessible peaks based on the footprint score.
    I hope my reply can help you.

Best,
Pin
